name: Terraform CD 

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment to use (e.g., staging, production)'
        required: true
        type: string


jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::670270766287:role/Github-AWS-EKS
          aws-region: eu-west-1   

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0
     

      - name: Change to ${{ inputs.env }} workspace
        run: cd workspaces/${{ inputs.env }}

      - name: Terraform Init (Stg)
        run:  terraform init

      - name: Terraform Validate (Stg)
        run:  terraform validate  

      - name: Terraform Plan ${{ inputs.env }}
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-${{ inputs.env }}
          path: tfplan

  apply:
    name: Terraform Apply 
    runs-on: ubuntu-latest
    needs: plan

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::670270766287:role/Github-AWS-EKS
          aws-region: eu-west-1   

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0

      - name: Change to ${{ inputs.env }} workspace
        run: cd workspaces/${{ inputs.env }}

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan-prod
          path: .

      - name: Terraform Apply 
        run: terraform apply tfplan

      - name: Trigger Workflow PROD CD
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'terraform-ci-cd-prod.yml',
              ref: 'main'
            })