name: TF format and validate

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment to use (e.g., staging, production)'
        required: true
        type: string

jobs:
  validate:
    name: Validate Terraform (${{ inputs.env }})
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::670270766287:role/Github-AWS-EKS
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.0

      - name: Change to ${{ inputs.env }} workspace
        run: cd workspaces/${{ inputs.env }}

      - name: Terraform Init (Stg)
        run: cd workspaces/${{ inputs.env }} && terraform init

      - name: Terraform Validate (Stg)
        run: cd workspaces/${{ inputs.env }} && terraform validate

      - name: List files
        run: ls -R  

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint (${{ inputs.env }})
        run: cd =workspaces/${{ inputs.env }} && tflint --init

      - name: Run TFLint (${{ inputs.env }})
        run: tflint --init && tflint --config=workspaces/${{ inputs.env }}/.tflint.hcl

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov (${{ inputs.env }})
        run:  checkov -d . --config-file=workspaces/${{ inputs.env }}/files/checkov.yml

      # - name: Run Checkov
      #   uses: bridgecrewio/checkov-action@v2
      #   with:
      #     directory: .
      #     config_file: files/checkov.yml  # Ensure this path is correct

      - name: Check Terraform Format
        run: cd workspaces/${{ inputs.env }} && terraform fmt -check