name: Terraform CI - Production

on:
  workflow_dispatch:
  permissions:
      id-token: write  # Autoriser l'écriture de JWT

jobs:
  validate:
    uses: ./.github/workflows/ci.yaml
    with:
      env: prod

  deploy:
    uses: ./.github/workflows/cd-prod.yaml
    with:
      env: prod
