name: Terraform CI - Staging

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Terraform (Stg)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Change to Staging workspace
        run: cd workspaces/staging

      - name: Terraform Init (Stg)
        run: terraform init -backend-config=workspaces/stg/backend.tfvars

      - name: Terraform Validate (Stg)
        run: terraform validate

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint (Stg)
        run: tflint --config=workspaces/stg/.tflint.hcl

      - name: Install Checkov
        run: |
          pip install checkov

      - name: Run Checkov (Stg)
        run: checkov -d . --config-file=workspaces/stg/checkov.yml

      - name: Check Terraform Format
        run: terraform fmt -check


      - name: Trigger Workflow STG CD
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'terraform-cd-stg.yml',
              ref: 'main'
            })